services:
  db:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cuisinotheque-net

  web:
    build: .
    container_name: django_app
    command: gunicorn cuisinotheque.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - cuisinotheque-net

volumes:
  postgres_data:
  media_data:

networks:
  cuisinotheque-net:
