apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuisinotheque-web
  namespace: cuisinotheque
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuisinotheque-web
  template:
    metadata:
      labels:
        app: cuisinotheque-web
    spec:
      containers:
        - name: web
          image: ghcr.io/wilfriedndr/cuisinotheque:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: DJANGO_SETTINGS_MODULE
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: ALLOWED_HOSTS
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: PORT
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 6

---
apiVersion: v1
kind: Service
metadata:
  name: cuisinotheque-web
  namespace: cuisinotheque
spec:
  selector:
    app: cuisinotheque-web
  ports:
    - port: 80
      targetPort: 8000
