apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuisinotheque-web
  namespace: cuisinotheque
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuisinotheque-web
  template:
    metadata:
      labels:
        app: cuisinotheque-web
    spec:
      containers:
        - name: web
          image: ghcr.io/wilfriedndr/cuisinotheque:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            # Variables Django
            - name: DJANGO_SETTINGS_MODULE
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: DJANGO_SETTINGS_MODULE
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY
            - name: ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: ALLOWED_HOSTS
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: PORT

            # Variables Postgres
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PORT

          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 6

---
apiVersion: v1
kind: Service
metadata:
  name: cuisinotheque-web
  namespace: cuisinotheque
spec:
  selector:
    app: cuisinotheque-web
  ports:
    - port: 80
      targetPort: 8000
