apiVersion: apps/v1
kind: Deployment
metadata:
  name: cuisinotheque-db
  namespace: cuisinotheque
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuisinotheque-db
  template:
    metadata:
      labels:
        app: cuisinotheque-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: cuisinotheque
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: cuisinotheque-db
