# Generated by Django 5.2.11 on 2026-02-12 19:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('profile', models.CharField(help_text='Pour qui et/ou par qui cette recette est conçue ?', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('cook_time_min', models.PositiveIntegerField(blank=True, help_text='Temps de cuisson (min, optionnel)', null=True)),
                ('rest_time_min', models.PositiveIntegerField(blank=True, help_text='Temps de repos (min, optionnel)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile'], name='recipes_rec_profile_32816d_idx'), models.Index(fields=['title'], name='recipes_rec_title_9ebae8_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecipeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=1)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='recipes.recipe')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('recipe', 'order')},
            },
        ),
        migrations.CreateModel(
            name='IngredientItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Quantité optionnelle (ex: 200 grammes)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(blank=True, help_text='Unité optionnelle (g, ml, càs, càc, pincée...)', max_length=30)),
                ('note', models.CharField(blank=True, help_text="Détails optionnels (ex: 'fondu', 'froid', 'à température ambiante')", max_length=180)),
                ('order', models.PositiveIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipesection')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('section', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140)),
                ('instruction', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('duration_min', models.PositiveIntegerField(blank=True, help_text='Durée estimée (min, optionnel)', null=True)),
                ('temperature_c', models.PositiveIntegerField(blank=True, help_text='Température (°C, optionnel)', null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipesection')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('section', 'order')},
            },
        ),
    ]
