# Generated by Django 5.2.11 on 2026-02-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cook_time_min',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='rest_time_min',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(blank=True, help_text="Temps de cuisson (ex: 25 min, 1h30, 20-25 min, jusqu'à doré...)", max_length=60),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rest_time',
            field=models.CharField(blank=True, help_text="Temps de repos (ex: 30 min, une nuit, jusqu'à refroidissement...)", max_length=60),
        ),
    ]
