# Generated by Django 5.2.11 on 2026-02-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_cook_time_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rest_time',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
