# Generated by Django 5.2.11 on 2026-02-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_cook_time_alter_recipe_rest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='profile',
            field=models.CharField(max_length=80),
        ),
    ]
